Sprint 2
dzhal/messenger pull request #3
Opened 2022-09-06 20:52 UTC by dzhal

2022-09-07 10:47 UTC, agadoev requested changes
Привет)
Спасибо за работу, все задания выполнены, но пока что еще есть, над чем поработать.

Сейчас в папке components лежат как компоненты, так и страницы. В папке страниц создаются инстансы страниц и инжектятся в DOM. По хорошему интансы страниц должны создаваться в одном файле (я оставил в нем комментарий), который является точкой входа в программу и там же нужно вставлять страницу в DOM

Это основное, что надо поправить. 
Я так же дал свои рекомендации о том, как лучше сделать handler'ы и валидацию. Если получится это реализовать, то дальше будет проще работать с кодом.

Давай поправим эти моменты и двинемся дальше :)

2022-09-07 10:47 UTC, agadoev commented on src/index.ts
> +// // import { registerAvatarComponent } from './components/avatar';
Закомментированный код в репозитории лучше не держать, он отвлекает внимание программиста и загрязняет кодовую базу. По хорошему в коде не должно быть ничего лишнего.

2022-09-07 10:47 UTC, agadoev commented on src/index.ts
> +// const root = document.getElementById('root');
Почему это закомментировано? Тут вполне нормальный, правильный код, который тут и должен быть

2022-09-07 10:47 UTC, agadoev commented on src/pages/login.ts
> +document.getElementById('root')?.append(fragment.getContent());
вставка страницы в DOM должна быть в src/index.ts. У приложения должна быть одна точка входа, а сейчас эта логика разбросана по разным файлам

2022-09-07 10:47 UTC, agadoev commented on src/utils/validateInput.ts
> +      return regexPassword.test(value);
Тут есть тонкий момент. Что, если требования к паролю изменятся? Я бы разбил валидацию пароля на несколько маленьких функций, каждая из которых проверяет что-то одно. Эти функции будут являться предикатами, т.е. принимать строку и возвращать boolean.
Так это выглядит у нас на проекте и с этим проще работать, чем с регуляркой. Так же эти правила можно использовать не только для пароля. Можешь попробовать сделать так же, если хочешь. Код станет гибче
```
const rules = {
  password: {
    required,
    hasDigit,
    hasLetter,
    minLength: minLength(8),
    hasSpecialSymbol,
  },
};
```

2022-09-07 11:58 UTC, dzhal commented on src/utils/block.ts
> +  private _meta: TMeta = <TMeta>{};
Нужно удалить? Я оставлял на случай если понадобится в дальнейшем в проекте

2022-09-07 12:03 UTC, dzhal commented on src/utils/custom-fetch.ts
> +  method?: typeof METHODS[keyof typeof METHODS];
К сожалению так не сработало, получаю тык от ТС:
```
type METHODS = /*unresolved*/ any
'METHODS' refers to a value, but is being used as a type here. Did you mean 'typeof METHODS'?
```

2022-09-07 12:11 UTC, dzhal commented on src/index.ts
> +// const root = document.getElementById('root');
так как нет роутинга, задумка отдельных html была в том, чтобы показать все сверстанные страницы по заданию
наставник обозначал такую возможность, и когда сделаем роутинг я вернусь к схеме одной точки входа

2022-09-07 12:59 UTC, dzhal commented on src/utils/custom-fetch.ts
> +  method?: typeof METHODS[keyof typeof METHODS];
переделал METHODS на enum - завелось

2022-09-07 18:50 UTC, dzhal commented on src/index.ts
> +// const root = document.getElementById('root');
Посоветовался с наставником - он сказал что можно оставить так до реализации роутов

2022-09-07 20:41 UTC, dzhal commented on src/utils/submitHandler.ts
> +import { validateInput } from './validateInput';
сделал п.п. 1

1. Я не совсем понял в чем мы выигрываем, если делаем мелкие разные валидаторы - нам так или иначе надо итерироваться по инпутам формы, проверять name и вызывать соответствующие валидаторы при сабмите
В текущем решении если что-то меняется, то мы меняем регулярку на инпут целиком, а не отдельные правила типа наличия заглавной буквы. Если добавляется поле, то добавляем соответствующий свитч-кейс
2. И не совсем понял как функцией заменить регулярку на например наличие кирилицы/латиницы в инпуте 
3. Если делать разные валидаторы для отдельных инпутов, то мне нужно прописывать свои хэндлеры для каждого инстанса компонента? Сейчас это все родительском компоненте

2022-09-09 14:55 UTC, agadoev approved these changes
Привет)
Отличная работа, валидация выглядит уже на порядок лучше. Работу принимаю, удачи в следующем спринте :)

2022-09-10 13:34 UTC, merged