Sprint 3
dzhal/messenger pull request #4
Opened 2022-09-25 13:50 UTC by dzhal

2022-09-26 13:19 UTC, podlovchenko requested changes
Привет, есть несколько замечаний
1. Нет работы с чатами
2. Нет валидации на странице изменения данных пользователя
3. Нельзя изменить данные пользователя
4. Нельзя изменить аватар
5. Нельзя изменить пароль

2022-11-14 18:05 UTC, dzhal commented
привет!

прошу прощения за недоделку в прошлый раз - отправлялось, чтобы уложиться в сроки отправки :(
к сожалению пропустил из-за известных событий полтора месяца, и сейчас постарался максимально добавить функциональности согласно чек-листу:
1. Работает апи чатов: добавление, удаление, добавление пользователя, удаление пользователя
2. Работает апи юзера: регистрация, авторизация, изменение данных пользователя, изменение пароля, изменение аватара, поиск юзера
3. Подключен вебсоккет сообщений

2022-11-15 09:55 UTC, podlovchenko approved these changes
Привет, спасибо за правки, работу принимаю)

2022-11-15 09:55 UTC, podlovchenko commented on package.json
>      "clear": "rm -rf dist .parcel-cache",
Команда rm -rf не будет работать на windows, можно использовать пакет https://www.npmjs.com/package/rimraf

2022-11-15 11:06 UTC, merged